version: '3.6'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn django_proj.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - postgresql
  postgresql:
#    restart: always
    image: sameersbn/postgresql:10-2
    ports:
      - 5432:5432
    environment:
      - DEBUG=true
      - DB_USER=private_db_user
      - DB_PASS=private_db_pass
      - DB_NAME=private_db_name
    volumes:
      - ./private-db-data:/var/lib/postgresql
  redis:
    image: sameersbn/redis:4.0.9-3
    ports:
      - 6379:6379
    command: "redis-server --appendonly yes --protected-mode no"


